### ISSUE TITLE
Address bar highlight color does not reflect accent setting.

### ISSUE THREAD

**Issue by SpicyCarrot1550** [mr-islam/zen-fox#16]
When text is highlighted in the address bar, the highlight color is always the default (magenta for light, cyan for dark), even when the accent color has been changed.

I have experienced this issue with Firefox 69.0.3 on Linux Mint 19.1 and on Firefox 70.0 on Linux Mint 19.2 
(version 1.9.3 of Zen Fox)

![Screenshot (Dark Theme)](https://user-images.githubusercontent.com/52430646/68076680-3fdad480-fd8e-11e9-928d-3f19808d6953.png)
![Screenshot (Light Theme)](https://user-images.githubusercontent.com/52430646/68076681-40736b00-fd8e-11e9-9552-1d3d596f3c4f.png)

**Comment by mr-islam** [comment]
Hi, thank you so much for a helpful and detailed issue report – it is very helpful and means a lot 😊

I have understood the problem and I am looking forward to fixing it ASAP—unfortunately, that probably won't be until Thursday this week at least, because I'm having my mid-term exams until then.

(I could try to do something quickly, but the last time I did that I pushed an update that broke the entire extension for all users 😅… since then I'm more cautious haha)

**Comment by SpicyCarrot1550** [comment]
No problem:)
I’m glad I could help.

**Comment by mr-islam** [comment]
Hi @SpicyCarrot1550, just wanted to let you know I have published an update fixing this issue (and some small others) 😊

Hope you have a great day!
