### ISSUE TITLE
Feature Request: automatic switching based on system dark mode

### ISSUE THREAD

**Issue by glward** [mr-islam/zen-fox#17]
Firefox itself now supports following the system dark mode, so if dark mode is enabled at the system level on macOS, or as a GTK theme (and probably on Windows?), it automatically switches to the default dark theme and vice-versa. It would be a nice enhancement to Zen Fox to support this in addition to time and weather based switching.

**Comment by mr-islam** [comment]
Great point, thanks for reminding me that Firefox supports this 👍 

I've updated the code to offer a new "Follow global system theme" method, and it's working great in my initial testing on a fresh install of Firefox.

Before publishing this update, I'd appreciate some more testing – would you mind trying out a quick test release? I've uploaded it on the Firefox Extension dashboard for signing now, and I'll post it here if you like. 

_I'm being cautious to release because it's been a while since I've worked on this project, so it's better to thoroughly make sure the update doesn't break anything 😅._

If the update works fine on your setup too, I'll go ahead and publish. I also need to:

- [x] update the readme
- [x] update the store listing

(By the way… would you happen to be the Garrett who posted one of the first reviews for this extension a few years back?)

EDIT: Their review is fast, nice! This is the signed and built release (you may need to change .zip to be `.xpi`, and install from the Add-ons menu → settings cog → install add-on from file):
[zenfox_solarized_dynamic_lightdark_theme-1.9.4-fx.zip](https://github.com/mr-islam/zen-fox/files/5552834/zenfox_solarized_dynamic_lightdark_theme-1.9.4-fx.zip)

**Comment by glward** [comment]
Just did a quick test on Linux and macOS Mojave and it seems to work well ... once I remembered to hit "save" on the settings page :P 

I'm just using xsettingsd on Linux, which is probably the edge case too, so I imagine it'll work well for people using more traditional DEs

And that probably wasn't me on the review -- I've only switched from Chrome to FF about a year and a half ago.

Thanks for the quick turnaround on this!

**Comment by mr-islam** [comment]
Thank you for testing so thoroughly 🤩! 

I have published the new version and it is available for all users now. Also finished updating the readme here and the Add-ons store listing.

Yes, the "save" behavior on the forms is less than ideal… I've just created a new issue for it #5 in case anyone wants to contribute. 

I'll close this issue now, thanks again and stay safe!

**Comment by glward** [comment]
@mr-islam seems like there's one bug with the "follow system theme" option: the Zen Fox theme isn't applied when Firefox starts, only when the system theme toggles from dark to light or vice-versa. Tested on both Linux and macOS, same thing

**Comment by mr-islam** [comment]
D'oh! I felt like I missed something in the implementation 😅

Will try get this done within the next few days, thank you for bringing up this key issue 👍🏽

**Comment by mr-islam** [comment]
Just spent some time working on this, first trying to re-produce the bug while looking at the logs

The current code would've done applied on startup anyway… but it seems firefox doesn't read the system theme until a second after zenfox checks it on startup

so i'll probably introduce some ugly wait period specific to this method…

**Comment by mr-islam** [comment]
Okay done! 👍🏽

From first setting the theme to starting up firefox, the system theme method will now reflect that correctly as well – as soon as v1.9.8.1 is live after review.

As noted above, on first start Firefox may briefly flicker through the wrong theme while Firefox correctly loads the current OS preference… there really isn't anything pretty or sustainable to do about this, so it will have to remain

**Comment by glward** [comment]
Much better, but it looks maybe one part of the theme isn't getting applied until I toggle still:

Fresh launch:
![2020-12-05-101220_1366x768_scrot](https://user-images.githubusercontent.com/494016/101246646-ab564a80-36e2-11eb-9e74-5e8961f920be.png)

After toggling to dark mode and back:
![2020-12-05-101244_1366x768_scrot](https://user-images.githubusercontent.com/494016/101246654-b610df80-36e2-11eb-9a28-037eb1a4afb0.png)

Minor issue but "white text on light background" isn't super easy on the eyes :P 

(May just be a Linux thing, too -- I can check on macOS in a bit)

**Comment by mr-islam** [comment]
Oh my, that's such an obvious bug I'm sad I missed it! Thank you for reporting it ❤

I have just re-created the same issue on Windows using the production release (the temporary build installed from the local file didn't cause this bug). 

I tried to see if the same issue happens when launching Firefox while the system is on dark mode, and it's the same (though much more readable than on the light theme):

![image](https://user-images.githubusercontent.com/17675428/101262533-9ca67c80-3750-11eb-880d-74821877ba65.png)

Applying the system theme method on startup actually revealed a subtler bug on how accents were being set for the addressbar popup highlights, one which I was unable to identify earlier and just gave up on! I have found it now and fixed it 👍🏽.

I also took this chance to try out a subtler `popup_highlight` design, one which I had originally intended:

![image](https://user-images.githubusercontent.com/17675428/101262828-6b2eb080-3752-11eb-8f3e-59dc7ad33e66.png)

![image](https://user-images.githubusercontent.com/17675428/101262836-7a156300-3752-11eb-941f-9d1ef8febec7.png)

What do you think about this?

I usually try to avoid making 'breaking' design changes like this that some users may dislike, but this feels like an upgrade overall to me. This popup address panel is only used when the user interacts with it, meaning it already has the user's attention and focus – so having a giant block of the accent color is not needed.

**Comment by mr-islam** [comment]
Just published an update to fix the highlighted option bug, and updated the style to be like my previous comment – I used it for a while and enjoyed it, and I hope all other users do as well :)

**Comment by glward** [comment]
Yeah, the new style looks nice to me as well. Thanks!

**Comment by mr-islam** [comment]
Glad to hear it, thank you for bringing all those bugs to attention and requesting this features in the first place!
