### ISSUE TITLE
Theme white pages (with some js)

### ISSUE THREAD

**Issue by BarbzYHOOL** [mr-islam/zen-fox#8]
Is it possible to theme all the white pages (like github, youtube, google etc) so they don't kill our eyes?

I suppose that it's not

**Comment by bricewge** [comment]
It seems to me that what you are looking for is [Stylish](https://addons.mozilla.org/en-US/firefox/addon/stylish/), a plugin which `"lets you customize any website with custom user styles"`.

**Comment by mr-islam** [comment]
Those plain white sites really are terrible!

But theming them is definitely outside the scope of this add-on (because Zen Fox only themes Firefox) — so a separate add-on/theme should do this. I'll close this issue here.

Userstyles are the way to go, like mentioned above!

You can take a look at [this userstyle](https://userstyles.org/styles/158210/solarized-light-global) and install it to your browser using [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/?src=search). It is *extremely* lazy and breaks many sites, but anyone (or you!) can modify it and restrict it to sites it is known to work on, or modify the CSS to refine it.

(also @BarbzYHOOL sorry for my late reply — I didn't even notice it until today because I got caught up in exams and that stuff :relieved:)
